### ISSUE TITLE
URGENT: https://www.r-consortium.org/all-projects/call-for-proposals is broken

### ISSUE THREAD

**Issue by HenrikBengtsson** [RConsortium/rconsortium_website#112]
The URL <https://www.r-consortium.org/all-projects/call-for-proposals> comes up first in search engines when searching for "R Consortium call for proposals". It is probably also used in recent Twitter, Mastodon, LinkedIn, ... announcements.

Since we have an on-going Call for Proposals, I think we should make this old URL work ASAP, e.g. have it redirect to the new <https://r-consortium.org/all-projects/callforproposals.html> URL.

**Comment by jcasman** [comment]
Confirmed this works from two different browsers and incognito window. Nice fix.
