### ISSUE TITLE
add ggsurvfit webinar

### ISSUE THREAD

**Issue by jcasman** [RConsortium/rconsortium_website#173]
Original is here: https://archive.r-consortium.org/r-medicine-webinar-visualizing-survival-data-with-the-ggsurvfit-r-package

Build separate page in the webinars directory. Example: https://r-consortium.org/webinars/r-insurance-series.html

Embed YouTube video. 

Bring over speaker picture locally. Make sure it has a clear, understandable file name like daniel.jpg

Update link on main webinars page: https://r-consortium.org/webinars/webinars.html

**Comment by sndaba** [comment]
Received.

**Comment by sndaba** [comment]
Hi Jesse, 
Please let me know if you have seen the new updates.

Simi

**Comment by jcasman** [comment]
Thank you for your work!

You need to first sync your fork with the R Consortium repo. Your fork is
75 commits behind the main R Consortium fork.

Unfortunately, I didn't notice this right away. I added some fixes to your
webinar page, mostly the link to the image still didn't include the images
directory. Totally minor, but the image was not displaying correctly.

[image: Screenshot 2024-10-27 at 8.19.41 AM.png]

Please make sure to always sync your fork first before anything. So you're
working with the latest version.

If you do it now and there are merge conflicts, please let me know. I'm
hoping there are no merge conflicts. :-)

**Comment by sndaba** [comment]
Hi,

What do I need to do now?
